<h1>My Address Book</h1>


<a href="<?php echo $this->url('address_book/default', array('controller' => 'addressbook', 'action' => 'create')); ?>">Create</a>
<table class="table">
<tr>
	<th>usr_id</th>
	<th>usr_name</th>
	<th>usr_email</th>
</tr>
<?php
	foreach ($rowset as $row) {
?>
		<tr>
			<td><?php  echo $row->usr_id; // The row is an ArrayObject $row->usr_id and $row['usr_id'] with both work?></td>
			<td><?php  echo $row['usr_name']; ?></td>
			<td><?php  echo $row['usr_email']; ?></td>
			<td><a href="<?php echo $this->url('address_book/default', array('controller' => 'addressbook', 'action' => 'update', 'id' => $row['usr_id'])); ?>">Edit</a></td>
			<td><a href="<?php echo $this->url('address_book/default', array('controller' => 'addressbook', 'action' => 'delete', 'id' => $row['usr_id']));?>" onclick="return confirm('Delete  <?php echo $row['usr_name']?>?')">Delete</a></td>
		</tr>
<?php
	}
?>
</table>